[package]
name = "chain-reader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures         = "0.1.31"
http            = "0.1.21" # must be compatible with the version rust-web3 uses
anyhow          = "1.0.42"
jsonrpc-core    = "14.2.0"
tokio-compat-02 = "0.2"
futures03       = { version = "0.3.1", package = "futures", features = ["compat"] }
log             = "0.4.14"
env_logger      = "0.9.0"
dotenv          = "0.15.0"
multiqueue      = "0.3.2"
broadcaster     = "1.0.0"
lazy_static     = "1.4.0"
hex             = { version = "0.4.3", default-features = false }
serde           = { version = "1.0", optional = false }
serde_json      = { version = "1.0", optional = false }
thiserror       = { version = "1.0", optional =false }
primitive-types = { version = "0.6.1", optional = true, features = ["codec"] }
itertools = "0.10"
prost = "0.8"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"
async-stream = "0.2"
rand = "0.7"
serde_yaml = "0.8"
hex-literal = "0.3"
clap = { version = "2.33.3", features = ["yaml"] }

massbit-chain-solana = { path = "../core/chain/solana" }
massbit-common = {path = "../core/common" }
massbit = {path = "../massbit" }
massbit-grpc = {path = "../core/grpc"}
chain-ethereum = {path = "../chain/ethereum" }
chain-solana = {path = "../chain/solana"}
ipfs-client = { path = "../core/ipfs-client" }

logger = { path = "../core/logger" }

tonic = "0.5"
prost-types = "0.8.0"
bs58 = "0.4.0"
[dependencies.codec]
package = "parity-scale-codec"
features = ["derive"]
version = "2.0.0"
default-features = false

[dependencies.solana-client]
package = "solana-client"
git = "https://github.com/massbitprotocol/solana.git"
branch = "massbit"

[dependencies.solana-transaction-status]
package = "solana-transaction-status"
git = "https://github.com/massbitprotocol/solana.git"
branch = "massbit"

[dependencies.solana-sdk]
package = "solana-sdk"
git = "https://github.com/massbitprotocol/solana.git"
branch = "massbit"

[dependencies.solana-program]
package = "solana-program"
git = "https://github.com/massbitprotocol/solana.git"
branch = "massbit"

[dependencies.web3]
package = "web3"
git = "https://github.com/graphprotocol/rust-web3"
branch = "master"


[build-dependencies]
tonic-build = "0.5"

[[bin]] # Bin to run gRPC server
name = "chain-reader"
path = "src/chain-reader.rs"

[[bin]] # Bin to run gRPC server
name = "client"
path = "example/client.rs"