version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'

  postgres:
    build: deployment/store
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres-massbit:/var/lib/postgresql/data

  metabase:
    build: deployment/metabase
    restart: always
    # Account for login can be found in the folder /metabase/setup-mb-account.sh
    entrypoint: ["./init.sh"]
    ports:
      - 3002:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: graph-node
      MB_DB_PORT: 5432
      MB_DB_USER: graph-node
      MB_DB_PASS: let-me-in
      MB_DB_HOST: postgres
    depends_on:
      - postgres
