[package]
name = "index-serum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.0", features = ["postgres"] }
plugin = { path = "../../../plugin/plugin" } #
massbit-chain-substrate = { path = "../../../core/chain/substrate"}
massbit-chain-solana = { path = "../../../core/chain/solana"}
index-store = { path = "../../../core/index-store"}
structmap = "0.1.5"
structmap-derive = "0.1.5"
chrono = "0.4.19"
uuid = { version = "0.8", features = ["serde", "v4"] }

[lib]
crate-type = ["cdylib"]