[package]
name = "ipfs-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
anyhow = "1.0"
http = "0.2.3"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
reqwest = { version = "0.10", features = ["json", "stream"] }
serde = { version = "1.0.126", features = ["rc", "derive"] }
serde_yaml = "0.8"
tokio = { version = "0.2.25", features = ["stream", "rt-threaded", "rt-util", "blocking", "time", "sync", "macros", "test-util", "net"] }
tokio-stream = { version = "0.1.6", features = ["sync"] }
tokio-retry = { git = "https://github.com/graphprotocol/rust-tokio-retry", branch = "update-to-tokio-02" }
log = "0.4.0"
env_logger = "0.8.4"