[package]
name = "store-postgres"
version = "0.1.0"
edition = "2018"
[lib]
name = "graphql"
path = "src/lib.rs"

[[bin]]
name = "graphql"
path = "src/main.rs"

[dependencies]
async-trait     = "0.1.48"
blake3          = "0.3.8"
chrono          = "0.4.19"
clap            = "2.33.3"
derive_more     = { version = "0.99.14" }
diesel          = { version = "1.4.7", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum  = { version = "1.1", features = ["postgres"] }
diesel_migrations   = "1.4.0"
env_logger          = "0.9.0"
exitcode            = "1.1.2"
fallible-iterator   = "0.1.4"
futures             = "0.1.21"

graphql-parser      = "0.3"
Inflector           = "0.11.3"
lazy_static         = "1.1"
log                 = "0.4.14"
lru_time_cache      = "0.11"
maybe-owned         = "0.3.4"
postgres            = "0.15"
rand                = "0.6.1"
serde               = "1.0"
uuid                = { version = "0.8.1", features = ["v4"] }
stable-hash         = { git = "https://github.com/graphprotocol/stable-hash" }
backtrace           = "0.3"
diesel_derives      = "1.4.1"
anyhow              = "1.0.41"
git-testament       = "0.2.0"
itertools           = "0.10.1"
serde_yaml          = "0.8.17"
serde_json          = "1.0.64"
[dependencies.graph]
package = "graph"
git = "https://github.com/graphprotocol/graph-node"
rev = "6d7e92a" #v0.22.0
#rev = "55d6150" #v0.23.0    #require async-trait vs 0.1.50 currently use v0.1.48
[dependencies.graph-graphql]
package = "graph-graphql"
git = "https://github.com/graphprotocol/graph-node"
rev = "6d7e92a" #v0.22.0

#[dependencies.graph-store-postgres]
#package = "graph-store-postgres"
#git = "https://github.com/graphprotocol/graph-node"
#rev = "6d7e92a" #v0.22.0

#[dependencies.graph-chain-ethereum]
#package = "graph-chain-ethereum"
#git = "https://github.com/graphprotocol/graph-node"
#rev = "6d7e92a" #v0.22.0

#[dependencies.graphql-parser]
#git = "https://github.com/graphql-rust/graphql-parser"
#rev="45167b53e9533c331298683577ba8df7e43480ac"

#[dev-dependencies]
#clap = "2.33.3"
#graphql-parser = "0.3"
#hex = "0.4.3"
#test-store = { path = "../../graphprotocol/graph-node/store/test-store" }
#hex-literal = "0.3"
#graph-mock = { path = "../../graphprotocol/graph-node/mock" }

[workspace]

[patch.crates-io]
# Include protection against stack overflow when parsing from this PR: https://github.com/graphql-rust/graphql-parser/commit/45167b53e9533c331298683577ba8df7e43480ac
graphql-parser = {git="https://github.com/graphql-rust/graphql-parser", rev="45167b53e9533c331298683577ba8df7e43480ac"}
