[package]
name = "massbit-store-postgres"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.50"
blake3 = "0.3.8"
derive_more = { version = "0.99.14" }
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2"] }
# We use diesel-dynamic-schema straight from git as the project has not
# made a release as a crate yet
diesel-dynamic-schema = { git = "https://github.com/diesel-rs/diesel-dynamic-schema", rev="a8ec4fb1" }
diesel-derive-enum = { version = "1.1", features = ["postgres"] }
diesel_migrations = "1.3.0"
fallible-iterator = "0.2.0"
futures = "0.1.21"
massbit = { path = "../../massbit" }
chain-ethereum = { path = "../../chain/ethereum" }
graphql-parser = "0.3"
Inflector = "0.11.3"
lazy_static = "1.1"
lru_time_cache = "0.11"
maybe-owned = "0.3.4"
postgres = "0.19.1"
rand = "0.6.1"
serde = "1.0"
uuid = { version = "0.8.1", features = ["v4"] }
stable-hash = { git = "https://github.com/graphprotocol/stable-hash" }
backtrace = "0.3"
diesel_derives = "1.4.1"
anyhow = "1.0.44"
git-testament = "0.2.0"
itertools = "0.10.1"
pin-utils = "0.1"

[dependencies.graph-graphql]
package = "graph-graphql"
git = "https://github.com/massbitprotocol/massbit-graph-node"
branch = "main"